import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Header from "./components/common/Header";

const InterFont = Inter({
  subsets: ["latin"],
  weight: ["200", "300", "400","500", "600", "700"]
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${InterFont.className} antialiased`}
      >
        <Toaster position="bottom-center"/>
        <div className="space-y-4">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
